export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_USER_ARTICLES = 'FETCH_USER_ARTICLES';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const UNMOUNT_ARTICLE = 'UNMOUNT_ARTICLE';